### ISSUE TITLE
The minskins 05/08/2020

### ISSUE THREAD

**Issue by WinterCore** [s0kil/Ruby_Tic_Tac_Toe#10]
Great project. 😀
I like the way you used the `curses` gem to make the game more interactive.
The code looks clean and organized overall.

One suggestion from @adfpizarro. is that you should only render the board when you get a keyboard interruption. That will increase the performance of the game overall. And you can use the saved CPU cycles to mine bitcoins.

![Bitcoin](https://i.giphy.com/media/QuspXi6Va6Scge0PB7/source.gif)

**Comment by s0kil** [comment]
@WinterCore Thank You.
@AdfPizarro Good Idea :+1:
