### ISSUE TITLE
Minskins #280720

### ISSUE THREAD

**Issue by simandebvu** [s0kil/Ruby_Tic_Tac_Toe#3]
**Awesome project !!!** ⭐ 👍 

https://github.com/danielsokil/Ruby_Tic_Tac_Toe/blob/67168ac2d60e16d782db73e47ad30901a8f2f3cd/bin/main#L22
Suggestion 🙏  Can you make this easier for the player to use ie.. maybe instead of prompting the players to enter 1.2 you can use just an integer.(1..9)

https://github.com/danielsokil/Ruby_Tic_Tac_Toe/blob/67168ac2d60e16d782db73e47ad30901a8f2f3cd/bin/main#L26

Can you try a different workaround to this as it makes the whole project easy to manipulate or alter? 🤔 

The great @Bismarck-GM has advised you to let the user select the symbol that they want to use in the beginning 👍. This will help you in writing tests in the future 😉 

@WinterCore suggests a descriptive gameplay guidelines ❓ 🎮

Just know that this golden retriever can wait to play !!!!

![GoldenRetrieverBored](https://i.giphy.com/media/YnZPEeeC7q6pQEZw1I/giphy.webp)

**Comment by s0kil** [comment]
Thanks For The Review!
